package sep

type IFTTTService interface {
	CreateParser()
	UpdateParser()
	ListParser()
	GetParser()
	DeleteParser()
	CreateParserDataSource()
	UpdateParserDataSource()
	ListParserDataSource()
	GetParserDataSource()
	DeleteParserDataSource()
	CreateDataSourceItem()
	ListDataSourceItem()
	DeleteDataSourceItem()
	CreateDestination()
	UpdateDestination()
	ListDestination()
	GetDestination()
	DeleteDestination()
	AttachParserDataSource()
	DetachParserDataSource()
	AttachDestination()
	DetachDestination()
	SaveScript()
	PublishScript()
	StartParser()
	StopParser()
}
