package dmp

type DeviceAdminService interface {
	RegisterDevice() error
	QueryClientIds()
	TransformClientId()
	DeleteClientIds()
	QueryDeviceDetail()
	BatchQueryDeviceDetail()
	QueryDevice()
	DeleteDevice()
	GetDeviceStatus()
	BatchGetDeviceState()
	DisableThing()
	EnableThing()
	ResetThing()
	BatchCheckDeviceNames()
	BatchRegisterDeviceWithApplyId()
	BatchRegisterDevice()
	QueryBatchRegisterDeviceStatus()
	QueryPageByApplyId()
	SaveDeviceProp()
	QueryDeviceProp()
	GetThingTopo()
	NotifyAddThingTopo()
	BatchAddThingTopo()
	RemoveThingTopo()
	QueryDeviceStatistics()
	GetGatewayBySubDevice()
	QueryDeviceByTags()
	QueryDeviceFileList()
	QueryDeviceFile()
	DeleteDeviceFile()
	BatchUpdateDeviceNickname()
	QueryLoRaJoinPermissions()
	CreateLoRaNodesTask()
	GetLoraNodesTask()
	QueryDeviceCert()
	QueryCertUrlByApplyId()
	QueryDeviceByStatus()
	QueryDeviceBySQL()
	ListOTAModuleVersionByDevice()
	ImportDevice()
	BatchImportDevice()
	BatchCheckImportDevice()
	QueryImportedDeviceByApplyId()
	BatchImportVehicleDevice()
	BatchCheckVehicleDevice()
	QueryVehicleDevice()
}

type DeviceDistributeService interface {
	CreateDeviceDistributeJob()
	CreateProductDistributeJOb()
	QueryDeviceDistributeDetail()
	QueryDeviceDistributeJob()
	ListDeviceDistributeJob()
	DeleteDeviceDistributeJob()
	ListDistributedDevice()
	ListDistributeProduct()
}

type DeviceTunnelService interface {
	CreateDeviceTunnel()
	CloseDeviceTunnel()
	DeleteDeviceTunnel()
	QueryDeviceTunnel()
}

type DeviceGroupService interface {
	CreateDeviceGroup()
	CreateDeviceDynamicGroup()
	DeleteDeviceGroup()
	DeleteDeviceDynamicGroup()
	UpdateDeviceGroup()
	QueryDeviceGroupInfo()
	QueryDeviceGroupList()
	QueryDynamicGroupDevices()
	BatchAddDeviceGroupRelations()
	SetDeviceGroupTags()
	QueryDeviceGroupTagList()
	QueryDeviceGroupByDevice()
	QueryDeviceListByDeviceGroup()
	QueryDeviceGroupByTags()
}
