:imagesdir: ../../../diagram/drawio
== 基础概念

image::k8s.dio.svg[]

=== Pod

Pod是可以再Kubernetes中创建和管理的、最小的可部署单元。
Pod是一组（一个或多个）容器；这些容器共享存储、网络、以及怎样运行这些容器的声明。Pod中的内容总是并置（colocated）的并且一同调度，在共享的上下文中运行。Pod所建模的是特定于应用的“逻辑主机”，其中包含一个或多个应用容器，这些容器是相对紧密的耦合在一起的。

除了应用容器，Pod还可以包含在Pod启动期间运行的 https://kubernetes.io/zh/docs/concepts/workloads/pods/init-containers/[Init容器]。也可以在集群中支持临时性容器的情况外，为调试的目的注入 https://kubernetes.io/zh/docs/concepts/workloads/pods/ephemeral-containers/[临时性容器]。

Kubernetes停止pod会经过如下五个步骤：

. pod切换到 **Terminating** 状态并且停止接受新流量，容器任然正常运行。
. **preStop** hook 发送指定的命令或者http请求到容器内部
. **SIGTERM** 发送sigterm信号给pod容器收到之后会有序退出
. Kubernetes 会给pod一个宽限期 （**grace period(terminationGracePeriodSeconds)**） 默认30s，并发执行preStop,SGTERM，如果在宽限期内没有结束，k8s会直接进入下一步
. **SIGKILL** 发送kill信号给pod，如果容器在超过宽限期依然存活，pod将被强制结束。

=== Deployments

一个 Deployment 控制器为 Pods和 ReplicaSets提供描述性的更新方式。

描述 Deployment 中的 desired state，并且 Deployment 控制器以受控速率更改实际状态，以达到期望状态。

Deployment负责管理Pod的生命周期管理、调度、多副本等问题，它可以根据我们的需求（比如通过标签）将Pod调度到目标机器上，调度完成之后它还会继续帮我们继续监控容器是否在正确运行，一旦出现问题，会立刻告诉我们Pod的运行不正常以及寻找可能的解决方案，比如目标节点不可用的时候它可以快速地调度到别的机器上去。另外，如果需要对应用扩容提升响应能力的时候，通过Deployment可以快速地进行扩展。

=== Service

将运行在一组 Pods 上的应用程序公开为网络服务的抽象方法。
使用 Kubernetes，您无需修改应用程序即可使用不熟悉的服务发现机制。 Kubernetes 为 Pods 提供自己的 IP 地址，并为一组 Pod 提供相同的 DNS 名， 并且可以在它们之间进行负载平衡。

它通过修改集群内部的路由规则，仅对集群内部有效。

四层负载均衡

=== ConfigMap

ConfigMap 是一种 API 对象，用来将非机密性的数据保存到键值对中。使用时， Pods 可以将其用作环境变量、命令行参数或者存储卷中的配置文件。
ConfigMap 将您的环境配置信息和 容器镜像 解耦，便于应用配置的修改。

=== Secret

Secret 对象类型用来保存敏感信息，例如密码、OAuth 令牌和 SSH 密钥。

=== Jobs

Job 会创建一个或者多个 Pods，并确保指定数量的 Pods 成功终止。 随着 Pods 成功结束，Job 跟踪记录成功完成的 Pods 个数。 当数量达到指定的成功个数阈值时，任务（即 Job）结束。 删除 Job 的操作会清除所创建的全部 Pods。

=== Cron Job

Cron Job 创建基于时间调度的 Jobs。

CronJobs 对于创建周期性的、反复重复的任务很有用，例如执行数据备份或者发送邮件。 CronJobs 也可以用来计划在指定时间来执行的独立任务，例如计划当集群看起来很空闲时 执行某个 Job。

=== DaemonSet

DaemonSet 确保全部（或者某些）节点上运行一个 Pod 的副本。 当有节点加入集群时， 也会为他们新增一个 Pod 。 当有节点从集群移除时，这些 Pod 也会被回收。删除 DaemonSet 将会删除它创建的所有 Pod。

DaemonSet 的一些典型用法：

* 在每个节点上运行集群存守护进程
* 在每个节点上运行日志收集守护进程
* 在每个节点上运行监控守护进程

=== Ingress

Ingress 是对集群中服务的外部访问进行管理的 API 对象，典型的访问方式是 HTTP。
Ingress 可以提供负载均衡、SSL 终结和基于名称的虚拟托管。

=== CNI(Container Network Interface)

=== CRI(Container Runtime Interface

统一容器运行时接口，凡是支持CRI的容器运行时，都可以作为K8s的底层容器运行时。

image::k8s_cri.dio.svg[]

如果使用Docker作为K8s容器运行时代话，kubelete需要先要通过dockershim去调用Docker，再通过Docker去调用containerd。

如果使用containerd作为K8s容器运行时，由于containerd内置了CRI插件，kubelet可以直接调用containerd。
)


