:imagesdir: ../../diagram/drawio
== CAP定理（布鲁尔定理）

> 在一个分布式系统中（值互相连接并共享数据的节点集合）中，当设计到读写操作时，智能保证Consistency（一致性）、Availability（可用性）、Partition tolerance（分区容错性），三者中的两个，另外一个必须被牺牲。

image::ha_cap.dio.svg[]

. CA满足的情况下，P不能满足

    数据同步（C）需要时间，也要正常的时间内响应（A），那么机器的数量就要少，所以P就不能满足

. CP满足的情况下，A不能满足

    数据同步（C）需要时间，机器数量也多（P），但是同步数据需要时间，所以不能再正常时间内响应，所以A就不满足

. AP满足的情况下，C不能满足

    机器数量也多（P），正常的时间内响应（A），那么数据就不能及时同步到其他节点，所以C不能满足


=== 一致性（Consistency）

一致性意思就是写操作之后进行读操作无论在哪个节点都需要返回写操作的值。
一致性有：强一致性、弱一致性、最终一致性


=== 可用性（Availability）

非故障的节点在合理的时间内返回合理的响应

=== 分区容错性

 当网络出现分区后，系统亦然能够继续履行职责

 在分布式的环境下，网络无法做到100%可靠，有可能出现故障，因此分区是一个必须的选项，如果选择了CA而放弃了P，若发生分区现象，为了保证C，系统需要禁止写入，此时就与A发生冲突，如果是为了保证A，则会出现正常的分区可以写入数据，有故障的分区不能写入数据，则与C就冲突了。因此分布式系统理论上不可能选择CA架构，而必须选择CP或AP架构。

== 分布式事务BASE理论

> BASE理论是Basically Available(基本可用)，Soft State（软状态）和Eventually Consistent（最终一致性）三个短语的缩写。

BASE理论是对CAP的延伸和补充，是对CAP中的AP方案的一个补充，即使在选择AP方案的情况下，如何更好的最终达到C。

基本内容：

* 基本可用（Basically Available）
* 软状态（Soft State）
* 最终一致性（Eventually Consistent）


== 附录

https://juejin.cn/post/6844903936718012430[神一样的CAP理论被应用在何方]