:imagesdir: ../../../../diagram/drawio
== 常规内存泄露问题的基本思路

image::gc_analysis_step.dio.svg[]

* *Dump Diff*
* *Leak Suspects*
* *内存Dump*: 使用jmpa、arthas等dump堆进行快照时记得摘掉流量，同时 *分别在CMS GC的发生前后分别dump一次*。
* *分析Top Component*：要记得按照对象、类、类加载器、包等多个维度观察Histogram
,同时使用outgoing和incoming分析关联对象，另外就是Soft Reference和Weak Reference、Finalizer等也要看一下。
* *分析 Unreachable*：重点看一下这个，关注下Shallow和Retained的大小。

== CMS

* 触发 CMS GC: 通过调用 *_collector->collect_in_background()* 进行触发Background GC
** CMS默认采用JVM运行时的统计数据判断是否需要触发CMS GC，如果需要根据 *-xx:CMSInitiatingOccupancyFraction* 的值进行判断，需要设置参数 *-xx:+UseCMSInitiationOccupancyOnly* 。
** 如果开启了 *-xx:UseCMSInitiatingOccupancyOnly* 参数，判断当前Old区使用率是否大于阈值，则触发CMS GC,该阈值可以通过参数 *-XX:CMSInitiatingOccupancyFraction* 进行设置，如果没有设置，默认为92%。
** 如果之前的Young GC失败过，或者下次Young区执行Young GC可能失败，这两种情况下需要触发CMS GC。
** CMS默认不会对MetaSpace或Perm进行垃圾收集，如果希望对这些区域进行垃圾收集，需要设置参数 *-XX:+CMSClassUnloadingEnabled* 。

* 触发 *Full GC* 
** 如果 *_full_gc_requested* 为真，说明有明确的需求进行GC，比如调用System.gc。
** 在Eden区为对象或TLAB分配内存失败，导致一次Young GC，在 *GenCollectorPolicy* 类的 *satisfy_failed_allocation()* 方法中进行判断。

* 触发 *YGC*
.. 新对象会先尝试在栈上分配，如果不行则尝试在TLAB分配，否则再看是否满足大对象条件要在老年代分配，最后才考虑在Eden区申请空间
.. 如果Eden区没有合适的空间，则触发YGC。
.. YGC时，对Eden区和From Survivor区的存活对象进行处理，如果满足动态年龄判断的条件或者To Survivor区空间不够则直接进入老年代，如果老年代空间也不够了，则会发生promotion failed，触发老年代的回收。否则将存活对象赋值到To Survivor区。
.. 此时Eden区和From Survivor区的剩余对象均为垃圾对象，可直接抹掉回收。

此外，老年代如果采用的是CMS回收器，为了减少CMS Remark阶段的耗时，也有可能触发一次YGC。

YGC采用的复制算法，主要分成以下两个步骤：

. 查找GC Roots，将其引用的对象拷贝到S1区
. 递归遍历第一步的对象，拷贝引用的对象到S1区或者晋升到Old区

可作为YGC时GC Root的对象包括以下几种：

. 虚拟机栈引用的对象
. 方法区中静态属性、常量引用对象
. 本地方法栈中引用的对象
. 被Sysnchronized锁持有的对象
. 记录当前被加载类的SystemDictionary
. 记录字符串常量引用的StringTable
. 存在跨代引用的对象
. 和GC Root处于同一CardTable的对象

image::jvm_eden.dio.svg[]

YGC在新生代中进行，首先要清楚新生代的堆结构划分。新生代分为Eden区和Survivor区，其中 *Eden:from:to=8:1:1*（可以通过 *-XX:SurvivorRatio*来设定），这是最基本的认识。

=== 为什么会有新生代？

如果不分代，所有对象全部在一个区域，每次GC都需要对全堆进行扫描，存在效率问题。分代后，可分别控制回收频率，并采用不同的回收算法，确保GC性能全局最优。

=== 为什么会采用复制算法？

新生代的对象朝生夕死，大约90%的新建对象可以被很快回收，复制算法成本低，同时还能保证空间没有碎片。虽然 *标记整理算法* 也可以保证没有碎片，但是由于新生代要清理的对象数量很大，将存活的对象整理到待清理对象之前，需要大量的移动操作，时间复杂度比复制算法高。

=== 为什么新生代需要两个Survivor区？

为了节省空间考虑，如果采用传统的复制算法，只有一个Survivor区，则Survivor区大小需要等于Eden区大小，此时空间消耗是 8*2，而两块Survuvor可以保持新对象始终在Eden区创建，存活对象在Survivor之间转移即可，空间消耗 8+1+1，明显后者空间利用率更高。

=== 新生代实际可用空间是多少？

YGC后，总有一块Survivor区是空闲的，因此新生代的可用内存空间是90%。

== G1

image::jvm_gc_g1.dio.svg[]

G1的混合回收过程中可以分为标记阶段、清理阶段和复制阶段

=== 标记阶段停顿分析

* 初始标记阶段：初始化标记阶段是值从GC Roots出发标记全部直接子节点的过程，该阶段是STW的，由于GC Roots数量不多，通常该阶段耗时非常短。
* 并发标记阶段：并发标记阶段是指从GC Roots开始对堆中对象进行可达性分析，找出存活对象。该阶段是并发的，即应用线程和GC线程可以同时活动。并发标记耗时相对长很多，但是因为不是STW，所以我们不太关心该阶段耗时的长短。
* 再标记阶段：重新标记哪些在并发标记阶段发生裱花的对象。该阶段是STW的。

=== 清理阶段停顿分析

* 清理阶段清点出有存活对象的分区和没有存活对象的分区，该阶段不会清理垃圾对象，也不会执行存活对象的复制。该阶段是STW的。

=== 复制阶段停顿分析

* 复制算法中的转移阶段需要分配新内存和复制对象的成员变量。转移阶段是STW的，其中内存分配通常耗时非常短，但对象成员变量的复制耗时有可能较长，这是因为复制耗时与存活对象数量与对象复杂度成正比。对象越复杂，复制耗时越长。

四个STW过冲中，初始化标记因为只标记GC Roots，耗时较短，再标记因为对象较少，耗时也较短。清理阶段因为内存分区数量少，耗时也较短。转移阶段要处理所有存活的对象，耗时会较长。因此，G1停顿时间的瓶颈主要是标记-复制中的转移阶段STW。为什么转移阶段不能和标记阶段一样并发执行呢？主要是G1未能解决转移过程中准确定位对象地址的问题。

G1的Young GC和CMS的Young GC，其标记-复制全过程STW，这里不再阐述。

== ZGC

> ZGC采用标记-复制算法，不过ZGC对该算法做了重大改进：ZGC在标记、转移和重定位阶段几乎都是并发的，这是ZGC实现停顿时间小于10ms目标的最关键原因

设计目标包括：

* 停顿时间不超过10ms（jdk16 < 1ms）
* 停顿时间不会随着堆的大小，或者活跃对象的大小而增加
* 支持8MB-4TB级别的堆（未来支持16TB）

垃圾回收周期如下图：

image:jvm_gc_zgc.dio.svg[]

ZGC只有三个STW阶段：*初始化标记*，*再标记*，*初始转移* 。其中，初始标记和初始转移分别都只需要扫描所有GC Roots，其处理时间和GC Roots的数量成正比，一般情况耗时非常短；再标记阶段STW时间很短，最多1ms，超过1ms则再次进入并发标记阶段。即，ZGC几乎所有停顿都依赖于GC Roots集合大小，停顿时间不会随着堆的大小伙子活跃对象的大小而增加。与ZGC对比，G1的转移阶段完全STW的，且停顿时间随存活对象的大小增加而增加。

=== ZGC关键技术

ZGC通过着色指针和读屏障技术，解决了转移过程中准确访问对象的问题，实现了并发转移。

image::jvm_gc_zgc_concurrent_step.dio.svg[]

着色指针和读屏障技术不仅应用在并发转移阶段，还应用在并发标记阶段：将对象设置为已标记，传统的垃圾回收期需要进行一次内存访问，并将对象存活信息放在对象头中；而在ZGC中，只需要设置指针地址的第42-45位即可，并且因为是寄存器访问，所以速度比访问内存更快。

== JDk16 ZGC

对比Jdk15的ZGC，jdk16中，GC几乎恒定的时间执行（O(1))，并且不会随堆，活动集或根集大小（或于此相关的任何其他内容）的增加而增加.

=== 关键技术：Stack Watermark Barrier

> 防止Java线程在栈帧中没有先检查是否安全就返回的机制。这是一个开销很低的检查，包括在已经存在的方法返回时的安全点检测中。概念上来说，你可以将它视为读屏障，在需要的时候它会强制Java线程在栈帧返回前采取某种类型的操作，使其进入安全状态。

从jdk16开始，线程堆栈的扫描和Java服务线程并发进行，这个过程不需要STW。

== 附录

* https://tech.meituan.com/2020/08/06/new-zgc-practice-in-meituan.html[新一代垃圾回收器ZGC的探索与实践]

* http://openjdk.java.net/jeps/376[JEP 376: ZGC: Concurrent Thread-Stack Processing]
