:imagesdir: ../../../static/img

= 事务

> 事务是由一组SQL语句组成的逻辑处理单元，事务具有以下4个属性，通常简称ACID属性。

* 原子性（Atomicity）

事务是一个原子操作单元，其对数据的修改，要么全部执行，要么全部不执行。

* 一致性（Consistent）

在事务开始和完成时，数据都必须保持一致状态。这意味着所有相关的数据规则都必须应用于事务的修改，以保持数据的完整性；事务结束时，所有的内部数据结构（如B树索引或双向链表）也都必须是正确的。

* 隔离性（Isolation）

数据库系统提供一定的隔离机制，保证事务在不受外部并发操作影响到“独立”环境执行。这意味着事务处理过程中的中间状态对外部是不可见的，反之亦然。

* 持久性（Durability）

事务完成之后，它对于数据的修改是永久性的，即使出现系统故障也能够保持。


== 事务隔离级别

|===
|隔离级别|隔离级别的值|导致的问题|用例

|Read-Uncommitted(读未提交)
|0
|有脏读
|

|Read-committed(读提交)
|1
|无脏读，允许不可重复读和幻读
|SqlServer、Oracle

|Repeatable-read（重复读）
|2
|无脏读和不可重复读，允许幻读
|Mysql Inndb

|Serializable（串行化）
|3
|都可以避免，执行效率慢，慎用
|
|===

* 脏读

事务A读取到了事务B已修改但尚未提交的数据，还在这个数据基础上做了操作。

* 不可重复读(前后多次读取内容不一致)

事务A第一次读取到数值a，第二次读取到了事务B已经提交的修改数值a`,不符合隔离性

* 幻读

第一个事务对一定范围的数据进行批量修改，第二个事务在这个范围内增加一条数据，这时候第一个事务就会丢失对新增数据的修改

[sql]
....
-- mysql中查看事务隔离级别的sql
show variables like 'tx_isolation';
....

== Distributed Transaction Coordinator(DTC,分布式事务)

=== 2PC
> Two Phase Commitment Protocol(两阶段提交协议)

image::oltp_dtc_2pc.dio.svg[]

事务管理器分2阶段协调资源：

1. 一阶段：准备
2. 二阶段：资源提交/回滚



=== TCC
> Try-Confirm-Cancel

image::oltp_dtc_tcc.dio.svg[]

一阶段：Try

二阶段：Confirm/Cancel

三个操作描述:

1. Try：检测预留资源
2. Confirm真正的业务操作提交
3. Cancel：预留资源释放

TCC实际上是服务化的两阶段提交协议，业务开发者需要实现这三个服务接口，第一阶段服务由业务代码编排来调用Try接口进行资源预留，所有参与者的Try接口都成功了，事务管理器会提交事务，并调用每个参与者的Confirm接口真正提交业务操作，否则调用每个参与者的Cancel接口回滚事务。

=== SAGA

Saga是一种补偿协议，在Saga模式下，分布式事务内多个参与者，每一个参与者都是一个冲正补偿服务，需要用户根据业务场景实现其正向操作和逆向操作。

Saga正向服务于补偿服务也需要业务开发者实现。

=== XA

== Seata(Simple Extensible Autonomous Transaction Architecture)

> Seata是一款开源的分布式事务解决方案，致力于提供高性能和简单易用的分布式事务服务。

image:oltp_dtc_seata.dio.svg[]

在Seata中，分布式事务的执行流程:

* TM开启分布式事务(TM向TC注册全局事务记录)
* 按业务场景，编排数据库、服务等事务内资源(RM向TC汇报资源准备状态);
* TM结束分布式事务，，事务一阶段结束(TM通知TC提交/回滚分布式事务);
* TC汇总事务信息，决定分布式事务是提交还是回滚
* TC通知所有RM提交/回滚资源，事务二阶段结束；

=== AT

AT模式是Seata中一种无侵入的分布式事务解决方案。在AT模式下，用户只需要关心自己的“业务SQL”，用户的“业务SQL”作为一阶段，Seata框架会自动生成事务的二阶段提交和回滚操作。

无侵入，有全局行锁，性能一般

