:imagesdir: ../../diagram/drawio

== 重试

image::mq_retry.dio.svg[]

问题：

. 破环消息顺序 
. 破坏跨边界事件发布到数据一致性
. 忽略不同类型的错误（可恢复，不可恢复）

如何改善：

* 消除错误类型

[source=java]
....
void processMessage(KafkaMessage km) {
    try {
        Message m = km.getMessage();
        transformAndSave(m);
    } catch (Throwable t) {
        if (isRecoverable(t)) {
            // ...
        } else {
            // ...
        }
    }
}
....

* 在消费者内重试可恢复错误

[source=java]
....
void processMessage(KafkaMeeesage km) {
    try {
        Message m = km.getMessage();
        transformAndSave(m);
    } catch(Throwable t) {
        if (osRecpverable(t)) {
            doWithRetry(m, Backoff.EXPONENTIAL, this::transformAndSave);
        } else {
            // ...
        }
    }
}
....

（注意：我们使用的任何退避机制都应配置为在达到某个阈值时向我们发出警报，并通知我们潜在的严重错误）

* 遇到不可恢复错误时，将消息直接发送到最后一个主题

* 考虑排序

需要确保属于同一聚合的后续消息也被隐藏。我们还应该考虑以下事实：固定的消费者处理了隐藏消息后，它扔可能会遇到其他错误。这种情况下，其错误处理行为应像我们之前描述的那样：

** 如果错误是可恢复的，则使用规避策略重试
** 如果错误是不可恢复的，它将隐藏消息并继续下一条。

* 可以接受一些数据不一致？

== 消息不丢失不重复

消费端重复消费：很容易解决，建立去重表
消费端丢失数据：也容易解决，关闭自动offset，处理完之后提交
生产端重复发送：这个不重要，消费端消费之前从去重表中判断就可以
生产端丢失数据：这个是最麻烦的情况
解决策略：
1. 异步方式缓冲区满了，就阻塞在那，等着缓冲区可用，不能情况缓冲区
2. 发送消息之后回调函数，发送成功就发送下一条，发送失败就记在日志中，等着定时脚本来扫描（发送失败可能并不真的发送失败，只是没有收到反馈，定时脚本可能会重发）